local lush = require("lush")
local hsl = lush.hsl

-- Mellow dark palette
local c = {
  bg = hsl("#161617"),
  fg = hsl("#c9c7cd"),
  bg_dark = hsl("#131314"),
  black = hsl("#27272a"),
  red = hsl("#f5a191"),
  teal = hsl("#85b5ba"),
  green = hsl("#90b99f"),
  yellow = hsl("#e6b99d"),
  blue = hsl("#aca1cf"),
  magenta = hsl("#e29eca"),
  cyan = hsl("#ea83a5"),
  white = hsl("#c1c0d4"),
  bright_black = hsl("#353539"),
  bright_red = hsl("#ffae9f"),
  bright_green = hsl("#9dc6ac"),
  bright_yellow = hsl("#f0c5a9"),
  bright_blue = hsl("#b9aeda"),
  bright_magenta = hsl("#ecaad6"),
  bright_cyan = hsl("#f591b2"),
  bright_white = hsl("#cac9dd"),
  gray00 = hsl("#18181a"),
  gray01 = hsl("#1b1b1d"),
  gray02 = hsl("#2a2a2d"),
  gray03 = hsl("#3e3e43"),
  gray04 = hsl("#57575f"),
  gray05 = hsl("#757581"),
  gray06 = hsl("#9998a8"),
  gray07 = hsl("#c1c0d4"),
  diag_error = hsl("#e06060"),
}

---@diagnostic disable: undefined-global
local theme = lush(function(injected_functions)
  local sym = injected_functions.sym

  return {
    -- =====================================================================
    -- UI Highlight Groups (:h highlight-groups)
    -- =====================================================================
    Normal({ fg = c.fg, bg = c.bg }),
    NormalNC({ fg = c.fg, bg = c.bg_dark }),
    NormalFloat({ fg = c.white, bg = c.gray00 }),
    FloatBorder({ fg = c.gray03, bg = c.bg }),
    FloatTitle({ fg = c.gray06, bg = c.bg, gui = "bold" }),
    ColorColumn({ bg = c.gray01 }),
    Conceal({ fg = c.gray06 }),
    Cursor({ fg = c.black, bg = c.fg }),
    lCursor({ fg = c.black, bg = c.fg }),
    CursorIM({ fg = c.black, bg = c.fg }),
    CursorLine({ bg = c.gray01 }),
    CursorColumn({ bg = c.gray01 }),
    Directory({ fg = c.blue }),
    DiffAdd({ bg = c.green, fg = c.black }),
    DiffChange({ fg = c.yellow, gui = "underline" }),
    DiffDelete({ bg = c.red, fg = c.black }),
    DiffText({ bg = c.yellow, fg = c.black }),
    EndOfBuffer({ fg = c.gray02 }),
    TermCursor({ fg = c.black, bg = c.fg }),
    TermCursorNC({ fg = c.black, bg = c.gray04 }),
    ErrorMsg({ fg = c.red }),
    VertSplit({ fg = c.gray02 }),
    WinSeparator({ fg = c.gray02 }),
    Folded({ fg = c.gray04 }),
    FoldColumn({ bg = c.bg, fg = c.gray05 }),
    SignColumn({ bg = c.bg, fg = c.gray05 }),
    IncSearch({ fg = c.black, bg = c.yellow }),
    CurSearch({ fg = c.black, bg = c.yellow }),
    Substitute({ fg = c.black, bg = c.yellow }),
    LineNr({ fg = c.gray04 }),
    LineNrAbove({ fg = c.gray04 }),
    LineNrBelow({ fg = c.gray04 }),
    CursorLineNr({ fg = c.gray06 }),
    CursorLineFold({ fg = c.gray05, bg = c.gray01 }),
    CursorLineSign({ bg = c.gray01, fg = c.gray05 }),
    MatchParen({ fg = c.yellow, gui = "underline" }),
    ModeMsg({ fg = c.gray03, gui = "bold" }),
    MsgArea({ fg = c.fg }),
    MsgSeparator({ fg = c.gray03 }),
    MoreMsg({ fg = c.bright_magenta }),
    NonText({ fg = c.gray05 }),
    Pmenu({ fg = c.white, bg = c.black }),
    PmenuSel({ fg = c.bright_white, bg = c.gray03 }),
    PmenuKind({ fg = c.cyan, bg = c.black }),
    PmenuKindSel({ fg = c.cyan, bg = c.gray03 }),
    PmenuExtra({ fg = c.gray05, bg = c.black }),
    PmenuExtraSel({ fg = c.gray06, bg = c.gray03 }),
    PmenuSbar({ bg = c.gray02 }),
    PmenuThumb({ bg = c.gray03 }),
    Question({ fg = c.blue }),
    QuickFixLine({ fg = c.cyan, bg = c.gray02 }),
    Search({ fg = c.bright_yellow, bg = c.black }),
    SpecialKey({ fg = c.gray04 }),
    SpellBad({ sp = c.diag_error, gui = "undercurl" }),
    SpellCap({ sp = c.yellow, gui = "undercurl" }),
    SpellLocal({ sp = c.yellow, gui = "undercurl" }),
    SpellRare({ sp = c.yellow, gui = "undercurl" }),
    StatusLine({ fg = c.white, bg = c.gray02 }),
    StatusLineNC({ fg = c.gray05, bg = c.gray02 }),
    TabLine({ fg = c.gray05 }),
    TabLineFill({ bg = c.black }),
    TabLineSel({ fg = c.white }),
    Title({ fg = c.green }),
    Visual({ bg = c.gray02 }),
    VisualNOS({ bg = c.gray02 }),
    WarningMsg({ fg = c.yellow }),
    Whitespace({ fg = c.gray03 }),
    WildMenu({ fg = c.black, bg = c.blue }),
    WinBar({ fg = c.white, bg = c.gray01 }),
    WinBarNC({ fg = c.gray05, bg = c.bg_dark }),

    -- =====================================================================
    -- Syntax Groups (:h group-name)
    -- =====================================================================
    Comment({ fg = c.gray05, gui = "italic" }),
    Constant({ fg = c.cyan }),
    String({ fg = c.green }),
    Character({ fg = c.green }),
    Number({ fg = c.magenta }),
    Boolean({ fg = c.yellow }),
    Float({ fg = c.magenta }),
    Identifier({ fg = c.fg }),
    Function({ fg = c.white }),
    Statement({ fg = c.white }),
    Conditional({ fg = c.blue }),
    Repeat({ fg = c.blue }),
    Label({ fg = c.blue }),
    Operator({ fg = c.yellow }),
    Keyword({ fg = c.blue }),
    Exception({ fg = c.blue }),
    PreProc({ fg = c.cyan }),
    Include({ fg = c.blue }),
    Define({ fg = c.cyan }),
    Macro({ fg = c.cyan }),
    PreCondit({ fg = c.cyan }),
    Type({ fg = c.yellow }),
    StorageClass({ fg = c.yellow }),
    Structure({ fg = c.yellow }),
    Typedef({ fg = c.yellow }),
    Special({ fg = c.blue }),
    SpecialChar({ fg = c.yellow }),
    Tag({ fg = c.yellow }),
    Delimiter({ fg = c.gray06 }),
    SpecialComment({ fg = c.gray05 }),
    Debug({ fg = c.yellow }),
    Underlined({ gui = "underline" }),
    Ignore({}),
    Error({ fg = c.red }),
    Todo({ fg = c.yellow, gui = "bold" }),

    -- =====================================================================
    -- Treesitter Highlight Groups
    -- =====================================================================
    sym("@boolean")({ fg = c.yellow }),
    sym("@constructor")({ fg = c.gray06 }),
    sym("@constant.builtin")({ fg = c.yellow }),
    sym("@keyword.function")({ fg = c.cyan }),
    sym("@keyword.import")({ fg = c.magenta }),
    sym("@keyword.type")({ fg = c.cyan }),
    sym("@namespace")({ fg = c.cyan }),
    sym("@parameter")({ fg = c.magenta }),
    sym("@property")({ fg = c.gray07 }),
    sym("@punctuation")({ fg = c.gray06 }),
    sym("@punctuation.delimiter")({ fg = c.gray06 }),
    sym("@punctuation.bracket")({ fg = c.gray06 }),
    sym("@punctuation.special")({ fg = c.gray06 }),
    sym("@string.documentation")({ fg = c.green }),
    sym("@string.regex")({ fg = c.blue }),
    sym("@string.escape")({ fg = c.magenta }),
    sym("@symbol")({ fg = c.yellow }),
    sym("@tag")({ fg = c.cyan }),
    sym("@tag.attribute")({ fg = c.teal }),
    sym("@tag.delimiter")({ fg = c.gray06 }),
    sym("@type.builtin")({ fg = c.magenta }),
    sym("@variable")({ fg = c.fg }),
    sym("@variable.builtin")({ fg = c.blue }),
    sym("@variable.member")({ fg = c.white }),
    sym("@variable.parameter")({ fg = c.magenta }),
    -- Language specific
    sym("@constructor.javascript")({ fg = c.cyan }),
    sym("@keyword.clojure")({ fg = c.bright_cyan }),

    -- Markup (markdown treesitter)
    sym("@markup.heading")({ fg = c.gray06, gui = "bold" }),
    sym("@markup.heading.1")({ fg = c.gray06, gui = "bold" }),
    sym("@markup.heading.1.marker")({ Comment }),
    sym("@markup.heading.2")({ fg = c.gray06, gui = "bold" }),
    sym("@markup.heading.2.marker")({ Comment }),
    sym("@markup.heading.3")({ fg = c.gray06, gui = "bold" }),
    sym("@markup.heading.3.marker")({ Comment }),
    sym("@markup.heading.4")({ fg = c.gray06, gui = "bold" }),
    sym("@markup.heading.4.marker")({ Comment }),
    sym("@markup.heading.5")({ fg = c.gray06, gui = "bold" }),
    sym("@markup.heading.5.marker")({ Comment }),
    sym("@markup.heading.6")({ fg = c.gray06, gui = "bold" }),
    sym("@markup.heading.6.marker")({ Comment }),
    sym("@markup.link")({ fg = c.gray06 }),
    sym("@markup.link.label")({ fg = c.cyan }),
    sym("@markup.link.url")({ fg = c.blue }),
    sym("@markup.list")({ fg = c.gray05, gui = "bold" }),
    sym("@markup.list.checked")({ fg = c.gray05 }),
    sym("@markup.list.unchecked")({ fg = c.gray05 }),
    sym("@markup.raw.block")({ fg = c.gray05 }),
    sym("@markup.raw.delimiter")({ fg = c.gray05 }),
    sym("@markup.quote")({ fg = c.gray06 }),
    sym("@markup.strikethrough")({ fg = c.gray04, gui = "strikethrough" }),

    -- =====================================================================
    -- LSP Semantic Token Groups
    -- =====================================================================
    sym("@lsp.type.boolean")({ sym("@boolean") }),
    sym("@lsp.type.builtinType")({ sym("@type.builtin") }),
    sym("@lsp.type.comment")({ Comment }),
    sym("@lsp.type.enum")({ Type }),
    sym("@lsp.type.enumMember")({ Constant }),
    sym("@lsp.type.escapeSequence")({ sym("@string.escape") }),
    sym("@lsp.type.formatSpecifier")({ sym("@punctuation.special") }),
    sym("@lsp.type.interface")({ Type }),
    sym("@lsp.type.keyword")({ Keyword }),
    sym("@lsp.type.namespace")({ sym("@namespace") }),
    sym("@lsp.type.number")({ Number }),
    sym("@lsp.type.operator")({ Operator }),
    sym("@lsp.type.parameter")({ sym("@parameter") }),
    sym("@lsp.type.property")({ sym("@property") }),
    sym("@lsp.type.selfKeyword")({ sym("@variable.builtin") }),
    sym("@lsp.type.typeAlias")({ Type }),
    sym("@lsp.type.variable")({ sym("@variable") }),
    sym("@lsp.type.unresolvedReference")({ sp = c.red, gui = "undercurl" }),
    sym("@lsp.typemod.class.defaultLibrary")({ sym("@type.builtin") }),
    sym("@lsp.typemod.enum.defaultLibrary")({ sym("@type.builtin") }),
    sym("@lsp.typemod.enumMember.defaultLibrary")({ sym("@constant.builtin") }),
    sym("@lsp.typemod.keyword.async")({ Keyword }),
    sym("@lsp.typemod.operator.injected")({ Operator }),
    sym("@lsp.typemod.string.injected")({ String }),
    sym("@lsp.typemod.type.defaultLibrary")({ sym("@type.builtin") }),
    sym("@lsp.typemod.variable.defaultLibrary")({ sym("@variable.builtin") }),
    sym("@lsp.typemod.variable.injected")({ sym("@variable") }),

    -- =====================================================================
    -- Diagnostics
    -- =====================================================================
    DiagnosticOk({ fg = c.green }),
    DiagnosticError({ fg = c.red }),
    DiagnosticWarn({ fg = c.yellow }),
    DiagnosticInfo({ fg = c.blue }),
    DiagnosticHint({ fg = c.blue }),
    DiagnosticUnderlineError({ sp = c.diag_error, gui = "undercurl" }),
    DiagnosticUnderlineWarn({ sp = c.yellow, gui = "undercurl" }),
    DiagnosticUnderlineInfo({ sp = c.blue, gui = "undercurl" }),
    DiagnosticUnderlineHint({ sp = c.blue, gui = "undercurl" }),
    DiagnosticVirtualTextError({ fg = c.red, bg = c.red.mix(c.bg, 90) }),
    DiagnosticVirtualTextWarn({ fg = c.yellow, bg = c.yellow.mix(c.bg, 90) }),
    DiagnosticVirtualTextInfo({ fg = c.blue, bg = c.blue.mix(c.bg, 90) }),
    DiagnosticVirtualTextHint({ fg = c.blue, bg = c.blue.mix(c.bg, 90) }),

    -- =====================================================================
    -- LSP
    -- =====================================================================
    LspReferenceText({ fg = c.blue, gui = "underline" }),
    LspReferenceRead({ fg = c.blue, gui = "underline" }),
    LspReferenceWrite({ fg = c.blue, gui = "underline" }),
    LspSignatureActiveParameter({ fg = c.yellow, gui = "bold" }),

    -- =====================================================================
    -- Treesitter Context
    -- =====================================================================
    TreesitterContext({ bg = c.gray01 }),
    TreesitterContextBottom({ sp = c.gray03, gui = "underdotted" }),
    TreesitterContextLineNumber({ fg = c.gray04, bg = c.gray01 }),

    -- =====================================================================
    -- Git Signs
    -- =====================================================================
    GitSignsAdd({ fg = c.green }),
    GitSignsChange({ fg = c.yellow }),
    GitSignsDelete({ fg = c.red }),

    -- =====================================================================
    -- Diff
    -- =====================================================================
    diffAdded({ fg = c.bright_green }),
    diffRemoved({ fg = c.bright_red }),
    diffChanged({ fg = c.bright_yellow }),
    diffOldFile({ fg = c.gray04 }),
    diffNewFile({ fg = c.white }),
    diffFile({ fg = c.gray05 }),
    diffLine({ fg = c.cyan }),
    diffIndexLine({ fg = c.magenta }),

    -- =====================================================================
    -- Telescope
    -- =====================================================================
    TelescopeBorder({ fg = c.bg, bg = c.bg }),
    TelescopeNormal({ fg = c.fg, bg = c.bg }),
    TelescopePreviewTitle({ fg = c.black, bg = c.green, gui = "bold" }),
    TelescopeResultsTitle({ fg = c.bg, bg = c.bg }),
    TelescopePromptTitle({ fg = c.black, bg = c.cyan, gui = "bold" }),
    TelescopePromptBorder({ fg = c.gray01, bg = c.gray01 }),
    TelescopePromptNormal({ fg = c.gray06, bg = c.gray01 }),
    TelescopePromptCounter({ fg = c.gray04, bg = c.gray01 }),
    TelescopeMatching({ fg = c.yellow, gui = "underline" }),

    -- =====================================================================
    -- Flash
    -- =====================================================================
    FlashBackdrop({ Comment }),
    FlashCurrent({ IncSearch }),
    FlashCursor({ bg = c.bright_blue, fg = c.bg_dark, gui = "bold" }),
    FlashLabel({ bg = c.cyan, fg = c.bg_dark, gui = "bold" }),
    FlashMatch({ Search }),
    FlashPrompt({ MsgArea }),
    FlashPromptIcon({ Special }),

    -- =====================================================================
    -- Cmp / Blink
    -- =====================================================================
    BlinkCmpLabelMatch({ fg = c.cyan, gui = "bold" }),
    CmpItemAbbrDeprecated({ fg = c.gray06, gui = "strikethrough" }),
    CmpItemAbbrMatch({ fg = c.cyan, gui = "bold" }),
    CmpItemAbbrMatchFuzzy({ fg = c.cyan, gui = "bold" }),
    CmpItemMenu({ fg = c.gray05 }),
    CmpItemKindText({ fg = c.gray06 }),
    CmpItemKindFunction({ fg = c.cyan }),
    CmpItemKindVariable({ fg = c.bright_white }),
    CmpItemKindEnum({ fg = c.green }),
    CmpItemKindSnippet({ fg = c.yellow }),

    -- =====================================================================
    -- Notify
    -- =====================================================================
    NotifyBackground({ fg = c.white, bg = c.bg }),
    NotifyERRORBorder({ fg = c.red, bg = c.bg }),
    NotifyWARNBorder({ fg = c.yellow, bg = c.bg }),
    NotifyINFOBorder({ fg = c.blue, bg = c.bg }),
    NotifyDEBUGBorder({ fg = c.gray06, bg = c.bg }),
    NotifyTRACEBorder({ fg = c.cyan, bg = c.bg }),
    NotifyERRORIcon({ fg = c.bright_red }),
    NotifyWARNIcon({ fg = c.bright_yellow }),
    NotifyINFOIcon({ fg = c.bright_blue }),
    NotifyDEBUGIcon({ fg = c.gray05 }),
    NotifyTRACEIcon({ fg = c.bright_cyan }),
    NotifyERRORTitle({ fg = c.bright_red }),
    NotifyWARNTitle({ fg = c.bright_yellow }),
    NotifyINFOTitle({ fg = c.bright_blue }),
    NotifyDEBUGTitle({ fg = c.gray05 }),
    NotifyTRACETitle({ fg = c.bright_cyan }),
    NotifyERRORBody({ fg = c.white, bg = c.bg }),
    NotifyWARNBody({ fg = c.white, bg = c.bg }),
    NotifyINFOBody({ fg = c.white, bg = c.bg }),
    NotifyDEBUGBody({ fg = c.white, bg = c.bg }),
    NotifyTRACEBody({ fg = c.white, bg = c.bg }),

    -- =====================================================================
    -- Illuminate
    -- =====================================================================
    IlluminatedWordText({ bg = c.gray03 }),
    IlluminatedWordRead({ bg = c.gray03 }),
    IlluminatedWordWrite({ bg = c.gray03 }),

    -- =====================================================================
    -- Hop / Leap
    -- =====================================================================
    HopNextKey({ fg = c.bright_yellow }),
    HopNextKey1({ fg = c.bright_blue }),
    HopNextKey2({ fg = c.bright_cyan }),
    HopUnmatched({ fg = c.gray04 }),
    HopCursor({ fg = c.bright_cyan }),
    HopPreview({ fg = c.bright_blue }),
    LeapLabel({ fg = c.bright_yellow, gui = "bold" }),
    LeapBackdrop({ fg = c.gray05 }),

    -- =====================================================================
    -- Dap UI
    -- =====================================================================
    DapUINormal({ Normal }),
    DapUIVariable({ Normal }),
    DapUIScope({ fg = c.blue }),
    DapUIType({ fg = c.magenta }),
    DapUIValue({ Normal }),
    DapUIModifiedValue({ fg = c.blue, gui = "bold" }),
    DapUIDecoration({ fg = c.blue }),
    DapUIThread({ fg = c.bright_green }),
    DapUIStoppedThread({ fg = c.blue }),
    DapUIFrameName({ Normal }),
    DapUISource({ fg = c.magenta }),
    DapUILineNumber({ fg = c.blue }),
    DapUIFloatNormal({ NormalFloat }),
    DapUIFloatBorder({ fg = c.blue }),
    DapUIWatchesEmpty({ fg = c.bright_cyan }),
    DapUIWatchesValue({ fg = c.bright_green }),
    DapUIWatchesError({ fg = c.bright_cyan }),
    DapUIBreakpointsPath({ fg = c.blue }),
    DapUIBreakpointsInfo({ fg = c.bright_green }),
    DapUIBreakpointsCurrentLine({ fg = c.bright_green, gui = "bold" }),
    DapUIBreakpointsLine({ DapUILineNumber }),
    DapUIBreakpointsDisabledLine({ fg = c.gray03 }),
    DapUICurrentFrameName({ DapUIBreakpointsCurrentLine }),
    DapUIStepOver({ fg = c.blue }),
    DapUIStepInto({ fg = c.blue }),
    DapUIStepBack({ fg = c.blue }),
    DapUIStepOut({ fg = c.blue }),
    DapUIStop({ fg = c.bright_cyan }),
    DapUIPlayPause({ fg = c.bright_green }),
    DapUIRestart({ fg = c.bright_green }),
    DapUIUnavailable({ fg = c.gray03 }),
    DapUIWinSelect({ fg = c.cyan, gui = "bold" }),
    DapUIEndofBuffer({ EndOfBuffer }),

    -- =====================================================================
    -- NeoTree
    -- =====================================================================
    NeoTreeFloatBorder({ fg = c.gray03, bg = c.bg }),
    NeoTreeFloatTitle({ fg = c.gray05, bg = c.gray07 }),
    NeoTreeTitleBar({ fg = c.gray05, bg = c.gray01 }),

    -- =====================================================================
    -- Navic
    -- =====================================================================
    NavicIconsFile({ fg = c.fg }),
    NavicIconsModule({ fg = c.yellow }),
    NavicIconsNamespace({ fg = c.fg }),
    NavicIconsPackage({ fg = c.fg }),
    NavicIconsClass({ fg = c.cyan }),
    NavicIconsMethod({ fg = c.blue }),
    NavicIconsProperty({ fg = c.green }),
    NavicIconsField({ fg = c.green }),
    NavicIconsConstructor({ fg = c.cyan }),
    NavicIconsEnum({ fg = c.cyan }),
    NavicIconsInterface({ fg = c.cyan }),
    NavicIconsFunction({ fg = c.blue }),
    NavicIconsVariable({ fg = c.magenta }),
    NavicIconsConstant({ fg = c.magenta }),
    NavicIconsString({ fg = c.green }),
    NavicIconsNumber({ fg = c.cyan }),
    NavicIconsBoolean({ fg = c.yellow }),
    NavicIconsArray({ fg = c.gray06 }),
    NavicIconsObject({ fg = c.gray06 }),
    NavicIconsKey({ fg = c.blue }),
    NavicIconsKeyword({ fg = c.blue }),
    NavicIconsNull({ fg = c.cyan }),
    NavicIconsEnumMember({ fg = c.green }),
    NavicIconsStruct({ fg = c.cyan }),
    NavicIconsEvent({ fg = c.cyan }),
    NavicIconsOperator({ fg = c.fg }),
    NavicIconsTypeParameter({ fg = c.green }),
    NavicText({ fg = c.white }),
    NavicSeparator({ fg = c.gray06 }),

    -- =====================================================================
    -- Mini
    -- =====================================================================
    MiniClueNextKeyWithPostkeys({ fg = c.cyan }),
    MiniFilesCursorLine({ bg = c.gray02, gui = "bold" }),
    MiniFilesTitleFocused({ fg = c.bright_green, gui = "bold" }),
    MiniMapNormal({ fg = c.gray04, bg = c.gray01 }),
    MiniPickMatchRanges({ fg = c.cyan, gui = "bold" }),
    MiniPickMatchCurrent({ bg = c.gray02, gui = "bold" }),
    MiniPickMatchMarked({ bg = c.gray04 }),
    MiniPickPrompt({ fg = c.blue, gui = "bold" }),
    MiniPickPromptPrefix({ fg = c.magenta, gui = "bold" }),
    MiniStarterInactive({ fg = c.gray04 }),
    MiniStarterItemBullet({ fg = c.gray04, gui = "bold" }),
    MiniStarterItemPrefix({ fg = c.magenta, gui = "bold" }),
    MiniStarterQuery({ fg = c.cyan, gui = "bold" }),
    MiniStarterSection({ fg = c.blue, gui = "bold" }),
    MiniStarterHeader({ fg = c.red, gui = "bold" }),
    MiniStatuslineModeNormal({ fg = c.bg, bg = c.cyan, gui = "bold" }),
    MiniStatuslineModeInsert({ fg = c.bg, bg = c.blue, gui = "bold" }),
    MiniStatuslineModeVisual({ fg = c.bg, bg = c.magenta, gui = "bold" }),
    MiniStatuslineModeCommand({ fg = c.bg, bg = c.yellow, gui = "bold" }),
    MiniStatuslineModeReplace({ fg = c.bg, bg = c.red, gui = "bold" }),
    MiniStatuslineModeTerminal({ fg = c.bg, bg = c.green, gui = "bold" }),
    MiniStatuslineModeOther({ fg = c.bg, bg = c.green, gui = "bold" }),
    MiniStatuslineFileinfo({ fg = c.gray06, bg = c.gray03 }),
    MiniStatuslineDevinfo({ fg = c.gray06, bg = c.gray03 }),
    MiniStatuslineFilename({ fg = c.white, gui = "bold" }),
    MiniTablineCurrent({ fg = c.blue, bg = c.bg, gui = "bold" }),
    MiniTablineFill({ bg = c.black }),
    MiniTablineVisible({ fg = c.gray06, bg = c.black, gui = "bold" }),
    MiniTablineModifiedCurrent({ fg = c.black, bg = c.blue, gui = "bold" }),
    MiniTablineModifiedHidden({ fg = c.black, bg = c.gray05, gui = "bold" }),
    MiniTablineModifiedVisible({ fg = c.black, bg = c.gray06, gui = "bold" }),
    MiniTablineTabpagesection({ fg = c.black, bg = c.green, gui = "bold" }),

    -- =====================================================================
    -- HTML
    -- =====================================================================
    htmlArg({ fg = c.bright_blue }),
    htmlEndTag({ fg = c.gray06 }),
    htmlTitle({ fg = c.gray07 }),
    htmlTag({ fg = c.gray06 }),
    htmlTagN({ fg = c.gray06 }),
    htmlTagName({ fg = c.cyan }),

    -- =====================================================================
    -- Markdown (vim syntax)
    -- =====================================================================
    markdownH1({ fg = c.bright_blue, gui = "bold" }),
    markdownH2({ fg = c.bright_blue, gui = "bold" }),
    markdownH3({ fg = c.bright_blue, gui = "bold" }),
    markdownH4({ fg = c.bright_blue, gui = "bold" }),
    markdownH5({ fg = c.bright_blue, gui = "bold" }),
    markdownH6({ fg = c.bright_blue, gui = "bold" }),
    markdownHeadingDelimiter({ fg = c.gray05 }),
    markdownHeadingRule({ fg = c.gray05 }),
    markdownId({ fg = c.cyan }),
    markdownIdDeclaration({ fg = c.blue }),
    markdownIdDelimiter({ fg = c.cyan }),
    markdownLinkDelimiter({ fg = c.gray05 }),
    markdownLinkText({ fg = c.blue }),
    markdownListMarker({ fg = c.gray05 }),
    markdownOrderedListMarker({ fg = c.gray05 }),
    markdownRule({ fg = c.gray05 }),
    markdownUrl({ fg = c.green }),
    markdownBlockquote({ fg = c.gray07 }),
    markdownBold({ fg = c.fg, gui = "bold" }),
    markdownItalic({ fg = c.fg, gui = "italic" }),
    markdownCode({ fg = c.yellow }),
    markdownCodeBlock({ fg = c.yellow }),
    markdownCodeDelimiter({ fg = c.gray05 }),
  }
end)

return theme
