return {}

-- return {
--   "epwalsh/obsidian.nvim",
--   version = "*",
--   lazy = true,
--   ft = "markdown",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--   },
--   opts = {
--     workspaces = {
--       {
--         name = "personal",
--         path = "~/Documents/Personal",
--       },
--       {
--         name = "league",
--         path = "~/Documents/notes/League",
--       },
--     },
--   },
-- }
